### PR TITLE
Gu: a few changes

### PR DESCRIPTION
**Pull request by josephmure**
This pull request does the following:

1. It breaks the code of GeneralLinearModelAlgorithm::computeReducedLogLikelihood down into several smaller methods. This corrects a small [mistake](https://github.com/jschueller/openturns/blob/5acbc83e4aa0efb900aa5b9bb0a54f85b0877d80/lib/src/Uncertainty/Algorithm/MetaModel/Kriging/GeneralLinearModelAlgorithm.cxx#L885): if a prior is used, then the likelihood should not depend on the ResourceMap key "GeneralLinearModelAlgorithm-UnbiasedVariance".
The methods added are [the following](https://github.com/josephmure/openturns/blob/0ae3e83643240ddac3d7e3fe9dbe0ff9485c8103/lib/src/Uncertainty/Algorithm/MetaModel/Kriging/openturns/GeneralLinearModelAlgorithm.hxx#L151):

```
  // Minimally reduced log-likelihood: only the trend parameter beta is replaced by its MLE
  void computeDetrendedLogLikelihood() const;

  // Correct logDeterminant_ if the likelihood is integrated: adds log(\det{FtR^{-1}F}) to logDeterminant_
  void correctIntegratedLikelihoodLogDeterminant() const;

  // If a prior is used, compute its value as a penalization term
  Scalar computeLogIntegratedLikelihoodPenalization() const;

  // Compute logarithm of integrated likelihood
  Scalar computeLogIntegratedLikelihood() const;

  // Update several terms of log-likelihood when the analytical amplitude is used.
  void AnalyticalAmplitudeUpdates() const;
```
2. It changes the way the log-posterior is computed by [removing unnecessary constants](https://github.com/josephmure/openturns/blob/0ae3e83643240ddac3d7e3fe9dbe0ff9485c8103/lib/src/Uncertainty/Algorithm/MetaModel/Kriging/GeneralLinearModelAlgorithm.cxx#L956). Constants are only removed if `scalePrior_ != NONE` however, because they do have meaning when no prior is used. This has the added advantage of making the output of computeReducedLogLikelihood equal to log_post from Gu's R package.

3. Gu changed the formula for the jointly robust prior: see [[Jointly Robust Prior for Gaussian Stochastic Process in Emulation, Calibration and Variable Selection, Mengyang Gu](https://arxiv.org/pdf/1804.09329.pdf)] (last paragraph of Section 3, page 15). This change is reflected in the new code.

4. Still concerning the jointly robust prior, a mistake regarding the computation of the dot [product dotCscale](https://github.com/josephmure/openturns/blob/0ae3e83643240ddac3d7e3fe9dbe0ff9485c8103/lib/src/Uncertainty/Algorithm/MetaModel/Kriging/GeneralLinearModelAlgorithm.cxx#L803) was corrected: dotCscale is not supposed to depend on the ScaleParametrization.

Finally, in order to debug the code in Python, I was forced to make a few methods of the class GeneralLinearModelAlgorithm public. I have not changed this yet but they should probably be made private again. Moreover, the new methods were made "protected", but I am not sure about this. Feedback would be welcome.

### CODE REVIEW

**Comment by jschueller** [comment]
there is too much bloat due to your debug traces to merge it as is, but I will try to integrate the corrections of formulas.

**Comment by josephmure** [comment]
I've removed all debug traces and corrected a mistake in GeneralLinearModelAlgorithm::computeHMatLogDeterminantCholesky().

**Comment by jschueller** [comment]
I'm confused because you're mixing structural changes and math changes.
Right now I'm trying to extract the math changes separately, I'll worry about the structure after.

**Comment by jschueller** [comment]
done
- using less functions
- new flat prior
- new formula for Ca in jointly robust-prior

**Pull request closed without merging**
