### PR TITLE
Gpd: improve doc

### PR DESCRIPTION
**Pull request by adutfoy**
Improvement of the doc Coles GPD

### CODE REVIEW

**Comment by adutfoy** [comment]
Julien,
I don't understand why the dev I propose are not compiled here..... There is only the job 'build' that has worked and the sphynx doc has not been produced for example....

**Comment by jschueller** [comment]
yes, the doc is not published in fork PRs 
I could try to integrate your changes so that you could see them from the main repo

**Comment by jschueller** [comment]
hello @adutfoy I integrated your changes, so they should be visible here: https://github.com/openturns/openturns/pull/2417

**Comment by adutfoy** [comment]
@jschueller : Hi Julien! I have completed my review. You can merge these modifications! Thanks!

**Comment by jschueller** [comment]
done

**Pull request closed without merging**
